### ISSUE TITLE
异步任务

### ISSUE THREAD

**Issue by Archeus123** [TogetherOS/cicada#15]
HttpDispatcher是阻塞式的，WorkAction中如果发起异步任务的话会有大麻烦。

**Comment by crossoverJie** [comment]
> HttpDispatcher是阻塞式的，WorkAction中如果发起异步任务的话会有大麻烦。

理解错了，我以为你指的是支持异步的 `HTTP` 响应。如果是在 `WorkAction` 中执行异步函数，那自行管理线程即可。

不知道你说的麻烦是什么？

**Comment by Archeus123** [comment]
@crossoverJie 可能你是对的
