### ISSUE TITLE
关于netty的一些建议

### ISSUE THREAD

**Issue by liweiyuan** [TogetherOS/cicada#16]
1.建议使用SimpleChannelInboundHandler<DefaultHttpRequest>取代ChannelInboundHandlerAdapter，避免请求消息体类型判断，方便后续扩展自定义的第三方的http请求
2.因为请求是无状态的，建议使用单例的模式，避免请求量大的时候创建过多的handler去处理请求消息
例子:
`public class RequestHandlerHandler extends SimpleChannelInboundHandler<Packet> {
    public static final IMHandler INSTANCE = new IMHandler();

    private Map<Byte, SimpleChannelInboundHandler<? extends Packet>> handlerMap;

    private IMHandler() {
        handlerMap = new HashMap<>();
        handlerMap.put(MESSAGE_REQUEST, MessageRequestHandler.INSTANCE);
        handlerMap.put(LOGIN_REQUEST, LoginRequestHandler.INSTANCE);
    }

    @Override
    protected void channelRead0(ChannelHandlerContext ctx, Packet packet) throws Exception {
        handlerMap.get(packet.getCommand()).channelRead(ctx, packet);
    }
}`

**Comment by crossoverJie** [comment]
@liweiyuan 

多谢建议，第一条可以后续优化。

第二条不是很理解，可以把内容格式化下，能否举个例子。

**Comment by cjqCN** [comment]
@liweiyuan @crossoverJie 
第二条的意思应该是多个channelPipeline共用一个httpDispatcher ，避免每次请求都创建handler。
代码大概如下：
```
public class CicadaInitializer extends ChannelInitializer<Channel> {

    HttpDispatcher httpDispatcher = new HttpDispatcher();

    @Override
    protected void initChannel(Channel ch) throws Exception {
        ch.pipeline()
                .addLast(new HttpRequestDecoder())
                .addLast(new HttpResponseEncoder())
                .addLast(httpDispatcher)
                .addLast("logging", new LoggingHandler(LogLevel.INFO));
    }
}
```
都是这里有个地方要注意：
共享的channel要添加 `@ChannelHandler.Sharable` 注解。
或者:
```
    @Override
    public boolean isSharable() {
        return true;
    }
```

**Comment by liweiyuan** [comment]
嗯，就是那个意思

**Comment by liweiyuan** [comment]
@cjqCN @crossoverJie 就是那个意思
