### ISSUE TITLE
Chain of responsibility

### ISSUE THREAD

**Issue by crossoverJie** [TogetherOS/cicada#18]
**Is your feature request related to a problem? Please describe.**
目前的拦截器只能处理一个拦截任务。

**Describe the solution you'd like**
利用责任链模式支持灵活拓展

**Comment by cjqCN** [comment]
我之前也在思考拦截器的设计这块。
有cicada现在的拦截器有几点看法：
- 不合理的地方 
  - 缺少拦截驳回的功能。
  - 不能设置拦截器的顺序。

- Support will be better
  -  IncludeUrlPatterns
  -  ExcludeUrlPatterns

我之前设计的[接口](https://github.com/cjqCN/htty/blob/master/htty-core/src/main/java/com/github/cjqcn/htty/core/interceptor/adapter/HttyInterceptorAdapter.java)是这样的：
```
public interface HttyInterceptorAdapter extends HttyInterceptorWrapper, Priority, UrlPatternMatchEnable {

    @Override
    default boolean preHandle(HttyRequest request, HttyResponse response) {
        return true;
    }

    @Override
    default void postHandle(HttyRequest request, HttyResponse response) {
    }

    @Override
    int getPriority();

    @Override
    Collection<String> getIncludeUrlPatterns();

    @Override
    Collection<String> getExcludeUrlPatterns();
}
```

能否用在cicada中，我提个pr？ 或者有其他想法？

**Comment by crossoverJie** [comment]
@cjqCN 见 #21
