### ISSUE TITLE
我maven导入依赖报错

### ISSUE THREAD

**Issue by yefengr** [TogetherOS/cicada#2]

**Comment by yefengr** [comment]
Failed to read artifact descriptor for top.crossoverjie.opensource:cicada-core:jar:1.0.0 less... (Ctrl+F1) 
Inspection info: Inspects a Maven model for resolution problems.

**Comment by crossoverJie** [comment]
@yefengr 

This is a problem with maven dependencies.

Please upgrade:


```java
<dependency>
    <groupId>top.crossoverjie.opensource</groupId>
    <artifactId>cicada-core</artifactId>
    <version>1.0.1</version>
</dependency>
```

> Also, please ask in English.
