### ISSUE TITLE
如果包路径和项目的包路径一样，configurationList中会有相同的元素

### ISSUE THREAD

**Issue by liweiyuan** [TogetherOS/cicada#20]
![image](https://user-images.githubusercontent.com/26542900/47010630-27435080-d172-11e8-9288-d4056b5d1659.png)

解决方法：
return configurationList.stream().distinct().collect(Collectors.toList())；

**Comment by crossoverJie** [comment]
> 如果包路径和项目的包路径一样

这个前提麻烦截个图呢。

**Comment by liweiyuan** [comment]
@crossoverJie 看错了。。。
