### ISSUE TITLE
读取配置文件的操作可否从action的execute里面抽离

### ISSUE THREAD

**Issue by bvcalf** [TogetherOS/cicada#27]
读取配置文件的操作能不能从action里面抽离，action里面只写业务逻辑，读取配置文件的操作在整个框架启动的时候实现。

搞个框架的生命周期啥的，可能实现起来相当困难，大佬可以酌情忽略

**Comment by crossoverJie** [comment]
@bvcalf 

是在启动的时候加载的。

https://github.com/TogetherOS/cicada/blob/1737ce82189614725f8d54dd1077a3011c85baa3/cicada-core/src/main/java/top/crossoverjie/cicada/server/config/CicadaSetting.java#L74-L98

你的意思是在 `action` 里连配置都不能获取？
这个就有点异想天开了，比如有些业务就是要根据配置文件里的配置来做不同的逻辑，这是很常见的需求；`SpringMVC` 大家也是这样用的。



> 搞个框架的生命周期啥的，可能实现起来相当困难

这个我不太懂是啥意思，但我觉得什么东西都不要**过度设计，为了设计而设计**。

简单、易用便是最好和不过时的（最近搞装修的感悟🤔）。
