### ISSUE TITLE
Got a null NullPointerException when APP starting!

### ISSUE THREAD

**Issue by leonGravel** [TogetherOS/cicada#28]
**Describe the bug**
if i set my  project structure like this:
```
   ├── src/main/java
   ├── ├──MainStart.java               //app start
```
i didn't set the package path, then,got this error:
```
ThreadLocalHolder.setLocalTime(System.currentTimeMillis());
 AppConfig.getInstance().setRootPackageName(clazz.getPackage().getName());
```
throw java.lang.NullPointerException.

**Expected behavior**
I think there should be a default value here instead of throwing an exception.

**Comment by crossoverJie** [comment]
@leonGravel 

Got it, I will update in the next version.

**Comment by crossoverJie** [comment]
@leonGravel 

#31 
fixed
