### ISSUE TITLE
为啥不做彻底一点，直接通过注解实例化bean

### ISSUE THREAD

**Issue by xiguizi** [TogetherOS/cicada#36]
通过注解也不需要手工去注册，启动时自动扫描需要注册实例化的bean，直接加载到内存，使用方便。

**Comment by crossoverJie** [comment]
@xiguizi 

现在就是扫描的注解实现的，不太懂什么意思。

    public static Map<String, Class<?>> getCicadaAction(String packageName) throws Exception {


        if (actionMap == null) {
            Set<Class<?>> clsList = getClasses(packageName);


            if (clsList == null || clsList.isEmpty()) {
                return actionMap;
            }


            actionMap = new HashMap<>(16);
            for (Class<?> cls : clsList) {


                Annotation annotation = cls.getAnnotation(CicadaAction.class);
                if (annotation == null) {
                    continue;
                }


                CicadaAction cicadaAction = (CicadaAction) annotation;
                actionMap.put(cicadaAction.value() == null ? cls.getName() : cicadaAction.value(), cls);


            }
        }
        return actionMap;
    }
