### ISSUE TITLE
RingBufferWheel  请问如何保证最后一个 Task 在 调用了 stop(false) 后还能被执行

### ISSUE THREAD

**Issue by starlai21** [TogetherOS/cicada#44]
RingBufferWheel  请问如何保证最后一个 Task 在 调用了 stop(false) 后还能被执行

**Comment by crossoverJie** [comment]
`RingBufferWheel` 的代码在 https://github.com/crossoverJie/cim 这个仓库中，请将 Issue 提到此处。

https://github.com/crossoverJie/cim/issues
