### ISSUE TITLE
怎么返回纯字符串内容不要JSON格式？

### ISSUE THREAD

**Issue by Sabirjan** [TogetherOS/cicada#8]
怎么返回纯字符串内容不要JSON格式？

**Comment by crossoverJie** [comment]
@Sabirjan 
The current version only supports response `JSON`.

Multiple response ways will be added in subsequent versions.

**Comment by Sabirjan** [comment]
我自己下载源码已经改了。WorkRes 加了一个属性type.
代表各种类型的输出，type=1默认 JSON ，其他的根据Type来获取类型
